service: react-notes-app-api

# use serverless-webpack plugin to transpile to ES6
plugins:
  - serverless-webpack

# enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  notes_create:
    handler: notes/create.main
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-identity:us-east-1:723184708744:identitypool/us-east-1:f9fb8dbe-f58f-4ddc-a2a3-a662779f6b9b

  notes_get:
    handler: notes/get.main
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-identity:us-east-1:723184708744:identitypool/us-east-1:f9fb8dbe-f58f-4ddc-a2a3-a662779f6b9b

  notes_list:
    handler: notes/list.main
    events:
      - http:
          path: notes
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-identity:us-east-1:723184708744:identitypool/us-east-1:f9fb8dbe-f58f-4ddc-a2a3-a662779f6b9b

  notes_update:
    handler: notes/update.main
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true
          authorizer:
            arn: arn:aws:cognito-identity:us-east-1:723184708744:identitypool/us-east-1:f9fb8dbe-f58f-4ddc-a2a3-a662779f6b9b

  notes_delete:
    handler: notes/delete.main
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:cognito-identity:us-east-1:723184708744:identitypool/us-east-1:f9fb8dbe-f58f-4ddc-a2a3-a662779f6b9b
